spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  zipkin:
    base-url: http://127.0.0.1:9411/
    
server:
  port: 8081

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/